import type { KnowledgePointStatus, QuizOption, QuizQuestion, QuizStats } from "../types";

// Matches the vault's pre-existing "study-quiz" convention (see
// .codex/skills/study-quiz/SKILL.md and the Archives/*.md files it
// produced) so quiz notes generated by KnowFlow stay readable/writable by
// that skill and by the Daily-Quiz Templater script that scans Archives/
// for "study-quiz" marker blocks and ```Answer fold``` code blocks.
const QUIZ_BLOCK_START = "<!-- study-quiz:start -->";
const QUIZ_BLOCK_END = "<!-- study-quiz:end -->";
const QUIZ_CALLOUT_TITLE = "> [!question]- Quiz";
const QUIZ_CALLOUT_TITLE_PATTERN = /^> \[!question\][+-]? Quiz\s*$/;

export interface QuizNoteMeta {
  sourcePath: string;
  category: string;
  createdAt: string;
}

export interface QuizAnswerState {
  selectedKey: string | null;
  correct: boolean | null;
  answeredAt: string | null;
}

/**
 * Quiz notes are plain Obsidian notes, not entries in data.json: the
 * question bank and every answer live in the vault as a normal markdown
 * file (one per source article), so they get Obsidian's native
 * search/backlinks/graph view for free and never grow the plugin's own
 * data file. Answering a question mutates the note's checkboxes in place
 * (see applyQuizAnswer) instead of appending to an ever-growing attempt
 * log — only the latest answer per question is kept, which is all the
 * stats/UI ever needed anyway.
 */
export function buildQuizNoteContent(meta: QuizNoteMeta, questions: QuizQuestion[]): string {
  const linkTarget = meta.sourcePath.replace(/\.md$/i, "");
  const frontmatter = [
    `考试日期: ${meta.createdAt.slice(0, 10)}`,
    "分类:",
    `  - ${meta.category || "未分类"}`,
    `原文: "[[${linkTarget}]]"`,
    "考试结果: false"
  ].join("\n");

  const blocks = questions.map((question, index) => renderQuestionBlock(question, index + 1)).join("\n\n");
  const body = [QUIZ_BLOCK_START, "", blocks, QUIZ_BLOCK_END].join("\n");
  return `---\n${frontmatter}\n---\n\n${body}\n`;
}

/** Replaces only the managed question bank, preserving knowledge points and other note content. */
export function upsertQuizQuestions(content: string, questions: QuizQuestion[]): string {
  const normalized = content.replace(/\r\n/g, "\n");
  const blocks = questions.map((question, index) => renderQuestionBlock(question, index + 1)).join("\n\n");
  const body = [QUIZ_BLOCK_START, "", blocks, QUIZ_BLOCK_END].join("\n");
  const start = normalized.indexOf(QUIZ_BLOCK_START);
  const markerEnd = normalized.indexOf(QUIZ_BLOCK_END);
  if (start >= 0 && markerEnd > start) {
    const end = markerEnd + QUIZ_BLOCK_END.length;
    return `${normalized.slice(0, start).trimEnd()}\n\n${body}\n${normalized.slice(end).trimStart()}`.trimEnd() + "\n";
  }
  return `${normalized.trimEnd()}\n\n${body}\n`;
}

/** Adds one targeted question without rewriting existing answers or knowledge points. */
export function appendQuizQuestion(content: string, question: QuizQuestion): string {
  const normalized = content.replace(/\r\n/g, "\n");
  const end = normalized.indexOf(QUIZ_BLOCK_END);
  if (end < 0) return upsertQuizQuestions(normalized, [question]);
  const displayIndex = splitQuestionBlocks(extractQuizBody(normalized) ?? "").length + 1;
  const block = renderQuestionBlock(question, displayIndex);
  return `${normalized.slice(0, end).trimEnd()}\n\n${block}\n${normalized.slice(end)}`;
}

/** Updates only the source-note wikilink in a generated quiz note. */
export function updateQuizSourcePath(content: string, sourcePath: string): string {
  const normalized = content.replace(/\r\n/g, "\n");
  const frontmatterMatch = /^---\n([\s\S]*?)\n---\n?/.exec(normalized);
  if (!frontmatterMatch || !/^原文:/m.test(frontmatterMatch[1])) return content;

  const linkTarget = sourcePath.replace(/\.md$/i, "");
  const nextFrontmatter = frontmatterMatch[1].replace(/^原文:.*$/m, `原文: "[[${linkTarget}]]"`);
  return `${normalized.slice(0, frontmatterMatch.index)}---\n${nextFrontmatter}\n---\n${normalized.slice(frontmatterMatch[0].length)}`;
}

export function buildQuizCallout(quizPath: string): string {
  const linkTarget = quizPath.replace(/\.md$/i, "");
  return `${QUIZ_CALLOUT_TITLE}\n> [[${linkTarget}|开始测试]]`;
}

export function parseQuizCallout(content: string): string | null {
  const lines = content.replace(/\r\n/g, "\n").split("\n");
  const range = findQuizCalloutRange(lines);
  if (!range) return null;
  const block = lines.slice(range.start + 1, range.end).join("\n");
  const link = />\s*\[\[([^|\]#]+)(?:#[^|\]]+)?(?:\|[^\]]*)?\]\]/.exec(block);
  if (!link) return null;
  const target = link[1].trim();
  return target.toLowerCase().endsWith(".md") ? target : `${target}.md`;
}

/** Keeps exactly one managed Quiz callout at the end of the source note. */
export function upsertQuizCallout(content: string, quizPath: string): string {
  const lines = content.replace(/\r\n/g, "\n").split("\n");
  const kept: string[] = [];
  let index = 0;
  while (index < lines.length) {
    if (QUIZ_CALLOUT_TITLE_PATTERN.test(lines[index])) {
      index += 1;
      while (index < lines.length && lines[index].startsWith(">")) index += 1;
      continue;
    }
    kept.push(lines[index]);
    index += 1;
  }
  const body = kept.join("\n").trimEnd();
  return `${body}${body ? "\n\n" : ""}${buildQuizCallout(quizPath)}\n`;
}

/** Reconstructs the structured question bank from a quiz note's markdown. */
export function parseQuizNote(content: string, notePath: string): QuizQuestion[] {
  const body = extractQuizBody(content);
  if (body === null) return [];
  const createdAt = extractFrontmatterField(content, "考试日期") ?? "";
  return splitQuestionBlocks(body)
    .map((block, index) => parseQuestionBlock(block, index, notePath, createdAt))
    .filter((question): question is QuizQuestion => question !== null);
}

/** Aggregates accuracy/wrong counts straight from checkbox state in the note. */
export function computeQuizStats(content: string): QuizStats {
  const body = extractQuizBody(content);
  if (body === null) return { total: 0, answered: 0, accuracy: null, wrong: 0 };
  const blocks = splitQuestionBlocks(body);
  if (blocks.length === 0) return { total: 0, answered: 0, accuracy: null, wrong: 0 };

  const answered = blocks.map(readAnswerStateFromBlock).filter((state) => state.selectedKey !== null);
  if (answered.length === 0) return { total: blocks.length, answered: 0, accuracy: null, wrong: 0 };

  const correct = answered.filter((state) => state.correct).length;
  return {
    total: blocks.length,
    answered: answered.length,
    accuracy: Math.round((correct / answered.length) * 100),
    wrong: answered.length - correct
  };
}

export function computeKnowledgePointStatuses(content: string): Record<string, KnowledgePointStatus> {
  const body = extractQuizBody(content);
  if (body === null) return {};
  const states = new Map<string, QuizAnswerState[]>();
  for (const block of splitQuestionBlocks(body)) {
    const answerBlock = /```Answer[^\n]*\n([\s\S]*?)```/.exec(block)?.[1] ?? "";
    const id = /^-\s*知识点[：:]\s*\[\[#\^([A-Za-z0-9-]+)\]\]/m.exec(answerBlock)?.[1];
    if (!id) continue;
    const values = states.get(id) ?? [];
    values.push(readAnswerStateFromBlock(block));
    states.set(id, values);
  }
  return Object.fromEntries(Array.from(states, ([id, values]) => {
    const answered = values.filter((state) => state.selectedKey !== null);
    if (answered.length === 0) return [id, "untested"];
    return [id, answered.every((state) => state.correct) ? "mastered" : "review"];
  }));
}

/**
 * Patches only the single question's option lines (uncheck all, check the
 * selected one, stamp it with ✅/❌ + date) and leaves every other line in
 * the file untouched — same minimal-diff approach as frontmatter-rules.ts.
 * `displayIndex` is 1-based, matching the "## N." heading written by
 * buildQuizNoteContent.
 */
export function applyQuizAnswer(content: string, displayIndex: number, selectedKey: string, correct: boolean, date: string): string {
  const range = findQuestionBlockRange(content, displayIndex);
  if (!range) return content;
  const block = content.slice(range.start, range.end);
  const patched = block.replace(
    /^- \[[ x]\] ([A-Z])\.\s+(.*?)(?:\s+[✅❌]\s+\S+)?$/gm,
    (_match, key: string, text: string) => {
      const cleanText = text.trim();
      return key === selectedKey
        ? `- [x] ${key}. ${cleanText} ${correct ? "✅" : "❌"} ${date}`
        : `- [ ] ${key}. ${cleanText}`;
    }
  );
  return content.slice(0, range.start) + patched + content.slice(range.end);
}

/** Patches the "考试结果" frontmatter flag in place without touching any other field. */
export function setExamPassed(content: string, passed: boolean): string {
  if (/^考试结果:\s*\S+/m.test(content)) {
    return content.replace(/^考试结果:\s*\S+/m, `考试结果: ${passed}`);
  }
  return content.replace(/^---\n/, `---\n考试结果: ${passed}\n`);
}

export function sanitizeQuizFileName(title: string): string {
  return title.replace(/[\\/:*?"<>|]/g, "-").replace(/\s+/g, " ").trim() || "Untitled";
}

function renderQuestionBlock(question: QuizQuestion, displayIndex: number): string {
  const optionLines = question.options.map((option) => `- [ ] ${option.key}. ${option.content}`);
  const explanation = (question.explanation || "暂无解析。").replace(/\s+/g, " ").trim();
  return [
    `## ${displayIndex}. ${question.question}`,
    "",
    ...optionLines,
    "",
    "```Answer fold",
    `- 答案：${question.answerKey}`,
    `- 难度：${question.difficulty}/5`,
    ...(question.knowledgePointId ? [`- 知识点：[[#^${question.knowledgePointId}]]`] : []),
    `- 解析：${explanation}`,
    "```"
  ].join("\n");
}

function findQuizCalloutRange(lines: string[]): { start: number; end: number } | null {
  const start = lines.findIndex((line) => QUIZ_CALLOUT_TITLE_PATTERN.test(line));
  if (start < 0) return null;
  let end = start + 1;
  while (end < lines.length && lines[end].startsWith(">")) end += 1;
  return { start, end };
}

function extractQuizBody(content: string): string | null {
  const start = content.indexOf(QUIZ_BLOCK_START);
  const end = content.indexOf(QUIZ_BLOCK_END);
  if (start === -1 || end === -1 || end <= start) return null;
  return content.slice(start + QUIZ_BLOCK_START.length, end);
}

function extractFrontmatterField(content: string, key: string): string | null {
  const match = new RegExp(`^${key}:\\s*(.+)$`, "m").exec(content);
  return match ? match[1].trim() : null;
}

function splitQuestionBlocks(body: string): string[] {
  return body
    .split(/\n(?=## \d+\.\s)/)
    .map((block) => block.trim())
    .filter((block) => /^## \d+\.\s/.test(block));
}

function findQuestionBlockRange(content: string, displayIndex: number): { start: number; end: number } | null {
  const startRegex = new RegExp(`^## ${displayIndex}\\.\\s`, "m");
  const startMatch = startRegex.exec(content);
  if (!startMatch) return null;
  const start = startMatch.index;

  const afterStart = content.slice(start + startMatch[0].length);
  const nextMatch = new RegExp(`^## ${displayIndex + 1}\\.\\s`, "m").exec(afterStart);
  const endMarkerIndex = afterStart.indexOf(QUIZ_BLOCK_END);

  let relativeEnd = afterStart.length;
  if (nextMatch) relativeEnd = Math.min(relativeEnd, nextMatch.index);
  if (endMarkerIndex !== -1) relativeEnd = Math.min(relativeEnd, endMarkerIndex);

  return { start, end: start + startMatch[0].length + relativeEnd };
}

function parseQuestionBlock(block: string, index: number, notePath: string, createdAt: string): QuizQuestion | null {
  const headingMatch = /^## \d+\.\s+(.+)$/m.exec(block);
  if (!headingMatch) return null;

  const options: QuizOption[] = [];
  const optionRegex = /^- \[[ x]\] ([A-Z])\.\s+(.*?)(?:\s+[✅❌]\s+\S+)?$/gm;
  let match: RegExpExecArray | null;
  while ((match = optionRegex.exec(block))) {
    options.push({ key: match[1], content: match[2].trim() });
  }
  if (options.length === 0) return null;

  const answerBlockMatch = /```Answer[^\n]*\n([\s\S]*?)```/.exec(block);
  const answerBlock = answerBlockMatch?.[1] ?? "";
  const answerKey = /^-\s*答案[：:]\s*([A-Z])/m.exec(answerBlock)?.[1] ?? options[0].key;
  const explanation = /^-\s*解析[：:]\s*(.+)$/m.exec(answerBlock)?.[1]?.trim() ?? "";
  const difficultyMatch = /^-\s*难度[：:]\s*(\d)/m.exec(answerBlock);
  const difficulty = difficultyMatch ? Number(difficultyMatch[1]) : 3;
  const knowledgePointId = /^-\s*知识点[：:]\s*\[\[#\^([A-Za-z0-9-]+)\]\]/m.exec(answerBlock)?.[1];

  return {
    id: `q${index + 1}`,
    notePath,
    ...(knowledgePointId ? { knowledgePointId } : {}),
    question: headingMatch[1].trim(),
    type: "single_choice",
    options,
    answerKey,
    explanation,
    difficulty,
    createdAt
  };
}

function readAnswerStateFromBlock(block: string): QuizAnswerState {
  const match = /^- \[x\] [A-Z]\.\s+.*?(?:\s+([✅❌])\s+(\S+))?$/m.exec(block);
  if (!match) return { selectedKey: null, correct: null, answeredAt: null };
  const keyMatch = /^- \[x\] ([A-Z])\./.exec(match[0]);
  return {
    selectedKey: keyMatch?.[1] ?? null,
    correct: match[1] ? match[1] === "✅" : null,
    answeredAt: match[2] ?? null
  };
}
